vich_uploader:
    db_driver: orm
    metadata:
        type: attribute



    mappings:
        oiseaux_images:
            uri_prefix: /images/oiseaux
            upload_destination: '%kernel.project_dir%/public/images/oiseaux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
